version: 2.1

orbs:
  elixir: membraneframework/elixir@dev:2fc0a8555daa6dfebe3f586cbbe5f10ede7b6aff

workflows:
  build:
    jobs:
      - elixir/build_test: &parameters
          executor: elixir
          filters:
            tags:
              only: /v.*/
      - elixir/test:
          <<: *parameters
      - elixir/lint:
          <<: *parameters
      - elixir/hex_publish:
          requires:
            - elixir/build_test
            - elixir/test
            - elixir/lint
          executor: elixir
          context:
            - Deployment
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v.*/
