version: 2.1

orbs:
  elixir: membraneframework/elixir@dev:f44d84633eb16f9ba9d0514ecabac716829953fe

workflows:
  build:
    jobs:
      - elixir/build_test: &parameters
          executor: elixir
          filters:
            tags:
              only: /v.*/
      - elixir/test:
          <<: *parameters
      - elixir/lint:
          <<: *parameters
      - elixir/hex_publish:
          requires:
            - elixir/build_test
            - elixir/test
            - elixir/lint
          executor: elixir
          context:
            - Deployment
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v.*/
