version: 2.0
jobs:
  build:
    docker:
      - image: membrane/membrane:latest
    environment:
      MIX_ENV: test
    working_directory: '~/app'

    steps:
      - checkout 
      - run: mix deps.get
      - run: mix format --check-formatted
      - run: mix compile --force --warnings-as-errors
      - run: mix dialyzer
      - run: mix credo
      - run: mix test
