version: 2.1

orbs:
  elixir: membraneframework/elixir@1.5.1

workflows:
  version: 2
  build:
    jobs:
      - elixir/build_test: &parameters
          executor: elixir
          filters:
            tags:
              only: /v.*/
      - elixir/test:
          <<: *parameters
      - elixir/lint:
          <<: *parameters
          cache-version: 2
      - elixir/hex_publish:
          requires:
            - elixir/build_test
            - elixir/test
            - elixir/lint
          executor: elixir
          context:
            - Deployment
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v.*/
