version: 2.1

orbs:
  elixir: membraneframework/elixir@dev:07f8105424b64df6eb288c2f8314b071f513b51a

workflows:
  build:
    jobs:
      - elixir/build_test: &parameters
          executor: elixir
          filters:
            tags:
              only: /v.*/
      - elixir/test:
          <<: *parameters
      - elixir/lint:
          <<: *parameters
      - elixir/hex_publish:
          requires:
            - elixir/build_test
            - elixir/test
            - elixir/lint
          executor: elixir
          context:
            - Deployment
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v.*/
