version: 2.1

orbs:
  elixir: membraneframework/elixir@dev:94bbc77eef4293223822a2f7f31b136ac0833b1f

workflows:
  version: 2
  build:
    jobs:
      - elixir/build_test: &parameters
          executor: elixir
          filters:
            tags:
              only: /v.*/
      - elixir/test:
          <<: *parameters
      - elixir/lint:
          <<: *parameters
      - elixir/hex_publish:
          requires:
            - elixir/build_test
            - elixir/test
            - elixir/lint
          executor: elixir
          context:
            - Deployment
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v.*/
