/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n6.0-25-g868af7d7a4-20230617"
#endif /* AVUTIL_FFVERSION_H */
